#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- super admin used to connect to database
    CREATE USER $DB_SCHEMA_OWNER NOINHERIT CREATEROLE LOGIN NOREPLICATION PASSWORD '$SCHEMA_USER_PASSWORD';
    CREATE SCHEMA IF NOT EXISTS $SCHEMA_NAME AUTHORIZATION $DB_SCHEMA_OWNER;
    GRANT CREATE ON DATABASE postgres TO $DB_SCHEMA_OWNER;
    ALTER USER $DB_SCHEMA_OWNER SET search_path = '$DB_SCHEMA';
EOSQL